---
- name: Using the IBM Spectrum Virtualize collection
  collections:
    - ibm.spectrum_virtualize
  gather_facts: no
  connection: local
  hosts: localhost
  vars:    
    - clustername: 10.x.x.x
    - domain: 
    - username: username
    - password: password

  tasks:
    - name: Run CLI commands on V7000..
      ibm_svc_vdisk:
        #command: "svcinfo lssystem"
        clustername: "{{ clustername }}"
        domain: "{{domain}}"
        username: "{{ username }}"
        password: "{{ password }}"
        name: ansible_vol
        state: present
        mdiskgrp: Pool_03
        size: "20"
        unit: gb
        log_path: /root/ibm_v7000/logs.debug
