---
- name: Find out the Ceph version
  hosts: ceph_nodes
  gather_facts: yes
  tasks:

    - name: Create a directory
      file:
        path: /ceph_hc
        state: directory

    - name: Run the version check command
      shell: "{{ item }} >> /ceph_hc/{{ inventory_hostname }}"
      with_items:
        - "ceph df"
        - "ceph osd pool ls"

    - name: Copy the version output from remote to local
      fetch:
        src: /ceph_hc/{{ inventory_hostname }}
        dest: /root/automation_projects/ansible-playbooks/ceph/{{ inventory_hostname }}
        flat: yes 
