---
- name: Find out the Ceph version
  hosts: ceph_nodes
  gather_facts: yes
  tasks:

    - name: Create a directory
      file:
        path: /ceph_ver
        state: directory

    - name: Run the version check command
      shell: ceph -v > /ceph_ver/{{ inventory_hostname }}

    - name: Copy the version output from remote to local
      fetch:
        src: /ceph_ver/{{ inventory_hostname }}
        dest: /root/automation_projects/ansible-playbooks/ceph/{{ inventory_hostname }}
        flat: yes 
