---
- name: Find out the Ceph version
  hosts: ceph_nodes
  gather_facts: yes
  
  vars_prompt:

    - name: command
      prompt: Please enter a ceph command to run on all nodes..
      private: no

  tasks:

    - name: Create a directory
      file:
        path: /ceph_hc
        state: directory

    - name: Run the version check command
      shell: "{{ command }} > /ceph_hc/{{ inventory_hostname }}"

    - name: Copy the version output from remote to local
      fetch:
        src: /ceph_hc/{{ inventory_hostname }}
        dest: /root/automation_projects/ansible-playbooks/ceph/{{ inventory_hostname }}
        flat: yes 
